var os   = require('os');
var util = require('util');

console.log('-------');
console.log("TMP Dir");
console.log(os.tmpDir());
console.log('-------');
console.log('Host Name');
console.log(os.hostname());
console.log('-------');
console.log('OS Type');
console.log(os.type());
console.log(os.platform());
console.log(os.arch());
console.log(os.release());
console.log('-------');
console.log('Uptime');
console.log(os.uptime());
console.log(util.inspect(os.loadavg()));
console.log('-------');
console.log('Memory');
console.log('total:');
console.log(os.totalmem());
console.log('free:');
console.log(os.freemem());
console.log('Memory');
console.log('-------');
console.log("CPU's");
console.log(util.inspect(util.inspect(os.cpus())));
console.log('-------');
console.log('Network');
console.log(util.inspect(os.networkInterfaces()));
console.log('-------');
